# Generated by Django 5.0.1 on 2024-01-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_match_team_a_alter_match_team_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myteams',
            name='player',
            field=models.ManyToManyField(to='app.player', verbose_name='Jogadores'),
        ),
        migrations.AlterField(
            model_name='player',
            name='initial_price',
            field=models.FloatField(verbose_name='Preço Inicial'),
        ),
    ]
