# Generated by Django 5.0.1 on 2024-01-25 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_myteams_player_alter_player_initial_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Partida', 'verbose_name_plural': 'Partidas'},
        ),
        migrations.AlterModelOptions(
            name='myteams',
            options={'verbose_name': 'Meu Time', 'verbose_name_plural': 'Meus Times'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Jogador', 'verbose_name_plural': 'Jogadores'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Time', 'verbose_name_plural': 'Times'},
        ),
    ]
